from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING

from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from .Chunk import Chunk


class ChunkingStrategy(str, Enum):
    FIXED_SIZE = "fixed_size"
    SEMANTIC = "semantic"


class DocumentType(str, Enum):
    PDF = "pdf"
    TXT = "txt"


class Document(SQLModel, table=True):
    id: int | None = Field(
        default=None, primary_key=True
    )  # Optional field as it is autogenerated
    file_name: str
    file_path: str
    file_size: int
    doc_type: DocumentType
    chunking_strat: ChunkingStrategy
    upload_date: datetime = Field(default_factory=datetime.now)
    total_chunk_count: int = 0

    chunks: list["Chunk"] = Relationship(back_populates="document")
