from datetime import datetime
from enum import Enum
from sqlmodel import SQLModel, Field, Relationship
from Chunk import ChunkingStrategy, Chunk


class DocumentType(str, Enum):
    PDF = "pdf"
    TXT = "txt"


class Document(SQLModel, table=True):
    id: int | None = Field(
        default=None, primary_key=True
    )  # Optional field as it is autogenerated
    file_name: str
    file_path: str
    file_size: int
    doc_type: DocumentType
    chunking_strat: ChunkingStrategy
    upload_date: datetime = Field(default_factory=datetime.now)
    total_chunk_count: int = 0

    chunks: list["Chunk"] = Relationship(back_populates="document")
